---
- name: apt-get update
  apt: update-cache=yes
       cache_valid_time=99360

- name: Install sudo
  apt: pkg=sudo 
       state=present

- name: Upload sudoers file
  copy: src=sudoers
        dest=/etc/sudoers
        validate='visudo -cf %s'
        mode=0440

- name: Create user
  user: name={{ user }}
        groups=sudo
        shell=/bin/bash

- name: Upload SSH key(s) for passwordless ssh
  authorized_key: user={{ user }}
                  key={{ key }}
                  state=present

